env: "dev"
port: ":8002"
db_config:
  db_host: "database"  # Use Docker service name
  db_port: "5432"      # Internal container port for PostgreSQL
  db_user: "postgres"
  db_pass: "sairam123"
  db_name: "blog_app"