env: "dev"
port: ":8002"
db_config:
  db_host: "localhost"  # Use Docker service name
  db_port: "5432"      # Internal container port for PostgreSQL
  db_user: "postgres"
  db_pass: "sairam123"
  db_name: "blog_app"
cloudinary_url: "cloudinary://225449981684299:IMjhYNw12ccO8j7L8IJxQuo63fQ@dqs5mosyk"